"""
Constants and mappings for the journal automation project.
"""

# ── ASJC MAP ──────────────────────────────────────────────────────────────
ASJC = {
    "10": ("Multidisciplinary", "Multidisciplinary"),
    "1000": ("Multidisciplinary", "Multidisciplinary"),
    "11": ("Agricultural and Biological Sciences", "General"),
    "1100": ("Agricultural and Biological Sciences", "General Agricultural and Biological Sciences"),
    "1101": ("Agricultural and Biological Sciences", "Agricultural and Biological Sciences (miscellaneous)"),
    "1102": ("Agricultural and Biological Sciences", "Agronomy and Crop Science"),
    "1103": ("Agricultural and Biological Sciences", "Animal Science and Zoology"),
    "1104": ("Agricultural and Biological Sciences", "Aquatic Science"),
    "1105": ("Agricultural and Biological Sciences", "Ecology, Evolution, Behavior and Systematics"),
    "1106": ("Agricultural and Biological Sciences", "Food Science"),
    "1107": ("Agricultural and Biological Sciences", "Forestry"),
    "1108": ("Agricultural and Biological Sciences", "Horticulture"),
    "1109": ("Agricultural and Biological Sciences", "Insect Science"),
    "1110": ("Agricultural and Biological Sciences", "Plant Science"),
    "1111": ("Agricultural and Biological Sciences", "Soil Science"),
    "12": ("Arts and Humanities", "General"),
    "1200": ("Arts and Humanities", "General Arts and Humanities"),
    "1201": ("Arts and Humanities", "Arts and Humanities (miscellaneous)"),
    "1202": ("Arts and Humanities", "History"),
    "1203": ("Arts and Humanities", "Language and Linguistics"),
    "1204": ("Arts and Humanities", "Archaeology"),
    "1205": ("Arts and Humanities", "Classics"),
    "1206": ("Arts and Humanities", "Conservation"),
    "1207": ("Arts and Humanities", "History and Philosophy of Science"),
    "1208": ("Arts and Humanities", "Literature and Literary Theory"),
    "1209": ("Arts and Humanities", "Museology"),
    "1210": ("Arts and Humanities", "Music"),
    "1211": ("Arts and Humanities", "Philosophy"),
    "1212": ("Arts and Humanities", "Religious studies"),
    "1213": ("Arts and Humanities", "Visual Arts and Performing Arts"),
    "13": ("Biochemistry, Genetics and Molecular Biology", "General"),
    "1300": ("Biochemistry, Genetics and Molecular Biology", "General Biochemistry, Genetics and Molecular Biology"),
    "1301": ("Biochemistry, Genetics and Molecular Biology", "Biochemistry, Genetics and Molecular Biology (miscellaneous)"),
    "1302": ("Biochemistry, Genetics and Molecular Biology", "Ageing"),
    "1303": ("Biochemistry, Genetics and Molecular Biology", "Biochemistry"),
    "1304": ("Biochemistry, Genetics and Molecular Biology", "Biophysics"),
    "1305": ("Biochemistry, Genetics and Molecular Biology", "Biotechnology"),
    "1306": ("Biochemistry, Genetics and Molecular Biology", "Cancer Research"),
    "1307": ("Biochemistry, Genetics and Molecular Biology", "Cell Biology"),
    "1308": ("Biochemistry, Genetics and Molecular Biology", "Clinical Biochemistry"),
    "1309": ("Biochemistry, Genetics and Molecular Biology", "Developmental Biology"),
    "1310": ("Biochemistry, Genetics and Molecular Biology", "Endocrinology"),
    "1311": ("Biochemistry, Genetics and Molecular Biology", "Genetics"),
    "1312": ("Biochemistry, Genetics and Molecular Biology", "Molecular Biology"),
    "1313": ("Biochemistry, Genetics and Molecular Biology", "Molecular Medicine"),
    "1314": ("Biochemistry, Genetics and Molecular Biology", "Physiology"),
    "1315": ("Biochemistry, Genetics and Molecular Biology", "Structural Biology"),
    "14": ("Business, Management and Accounting", "General"),
    "1400": ("Business, Management and Accounting", "General Business, Management and Accounting"),
    "1401": ("Business, Management and Accounting", "Business, Management and Accounting (miscellaneous)"),
    "1402": ("Business, Management and Accounting", "Accounting"),
    "1403": ("Business, Management and Accounting", "Business and International Management"),
    "1404": ("Business, Management and Accounting", "Management Information Systems"),
    "1405": ("Business, Management and Accounting", "Management of Technology and Innovation"),
    "1406": ("Business, Management and Accounting", "Marketing"),
    "1407": ("Business, Management and Accounting", "Organizational Behavior and Human Resource Management"),
    "1408": ("Business, Management and Accounting", "Strategy and Management"),
    "1409": ("Business, Management and Accounting", "Tourism, Leisure and Hospitality Management"),
    "1410": ("Business, Management and Accounting", "Industrial Relations"),
    "15": ("Chemical Engineering", "General"),
    "1500": ("Chemical Engineering", "General Chemical Engineering"),
    "1501": ("Chemical Engineering", "Chemical Engineering (miscellaneous)"),
    "1502": ("Chemical Engineering", "Bioengineering"),
    "1503": ("Chemical Engineering", "Catalysis"),
    "1504": ("Chemical Engineering", "Chemical Health and Safety"),
    "1505": ("Chemical Engineering", "Colloid and Surface Chemistry"),
    "1506": ("Chemical Engineering", "Filtration and Separation"),
    "1507": ("Chemical Engineering", "Fluid Flow and Transfer Processes"),
    "1508": ("Chemical Engineering", "Process Chemistry and Technology"),
    "16": ("Chemistry", "General"),
    "1600": ("Chemistry", "General Chemistry"),
    "1601": ("Chemistry", "Chemistry (miscellaneous)"),
    "1602": ("Chemistry", "Analytical Chemistry"),
    "1603": ("Chemistry", "Electrochemistry"),
    "1604": ("Chemistry", "Inorganic Chemistry"),
    "1605": ("Chemistry", "Organic Chemistry"),
    "1606": ("Chemistry", "Physical and Theoretical Chemistry"),
    "1607": ("Chemistry", "Spectroscopy"),
    "17": ("Computer Science", "General"),
    "1700": ("Computer Science", "General Computer Science"),
    "1701": ("Computer Science", "Computer Science (miscellaneous)"),
    "1702": ("Computer Science", "Artificial Intelligence"),
    "1703": ("Computer Science", "Computational Theory and Mathematics"),
    "1704": ("Computer Science", "Computer Graphics and Computer-Aided Design"),
    "1705": ("Computer Science", "Computer Networks and Communications"),
    "1706": ("Computer Science", "Computer Science Applications"),
    "1707": ("Computer Science", "Computer Vision and Pattern Recognition"),
    "1708": ("Computer Science", "Hardware and Architecture"),
    "1709": ("Computer Science", "Human-Computer Interaction"),
    "1710": ("Computer Science", "Information Systems"),
    "1711": ("Computer Science", "Signal Processing"),
    "1712": ("Computer Science", "Software"),
    "18": ("Decision Sciences", "General"),
    "1800": ("Decision Sciences", "General Decision Sciences"),
    "1801": ("Decision Sciences", "Decision Sciences (miscellaneous)"),
    "1802": ("Decision Sciences", "Information Systems and Management"),
    "1803": ("Decision Sciences", "Management Science and Operations Research"),
    "1804": ("Decision Sciences", "Statistics, Probability and Uncertainty"),
    "19": ("Earth and Planetary Sciences", "General"),
    "1900": ("Earth and Planetary Sciences", "General Earth and Planetary Sciences"),
    "1901": ("Earth and Planetary Sciences", "Earth and Planetary Sciences (miscellaneous)"),
    "1902": ("Earth and Planetary Sciences", "Atmospheric Science"),
    "1903": ("Earth and Planetary Sciences", "Computers in Earth Sciences"),
    "1904": ("Earth and Planetary Sciences", "Earth-Surface Processes"),
    "1905": ("Earth and Planetary Sciences", "Economic Geology"),
    "1906": ("Earth and Planetary Sciences", "Geochemistry and Petrology"),
    "1907": ("Earth and Planetary Sciences", "Geology"),
    "1908": ("Earth and Planetary Sciences", "Geophysics"),
    "1909": ("Earth and Planetary Sciences", "Geotechnical Engineering and Engineering Geology"),
    "1910": ("Earth and Planetary Sciences", "Oceanography"),
    "1911": ("Earth and Planetary Sciences", "Paleontology"),
    "1912": ("Earth and Planetary Sciences", "Space and Planetary Science"),
    "1913": ("Earth and Planetary Sciences", "Stratigraphy"),
    "20": ("Economics, Econometrics and Finance", "General"),
    "2000": ("Economics, Econometrics and Finance", "General Economics, Econometrics and Finance"),
    "2001": ("Economics, Econometrics and Finance", "Economics, Econometrics and Finance (miscellaneous)"),
    "2002": ("Economics, Econometrics and Finance", "Economics and Econometrics"),
    "2003": ("Economics, Econometrics and Finance", "Finance"),
    "21": ("Energy", "General"),
    "2100": ("Energy", "General Energy"),
    "2101": ("Energy", "Energy (miscellaneous)"),
    "2102": ("Energy", "Energy Engineering and Power Technology"),
    "2103": ("Energy", "Fuel Technology"),
    "2104": ("Energy", "Nuclear Energy and Engineering"),
    "2105": ("Energy", "Renewable Energy, Sustainability and the Environment"),
    "22": ("Engineering", "General"),
    "2200": ("Engineering", "General Engineering"),
    "2201": ("Engineering", "Engineering (miscellaneous)"),
    "2202": ("Engineering", "Aerospace Engineering"),
    "2203": ("Engineering", "Automotive Engineering"),
    "2204": ("Engineering", "Biomedical Engineering"),
    "2205": ("Engineering", "Civil and Structural Engineering"),
    "2206": ("Engineering", "Computational Mechanics"),
    "2207": ("Engineering", "Control and Systems Engineering"),
    "2208": ("Engineering", "Electrical and Electronic Engineering"),
    "2209": ("Engineering", "Industrial and Manufacturing Engineering"),
    "2210": ("Engineering", "Mechanical Engineering"),
    "2211": ("Engineering", "Mechanics of Materials"),
    "2212": ("Engineering", "Ocean Engineering"),
    "2213": ("Engineering", "Safety, Risk, Reliability and Quality"),
    "2214": ("Engineering", "Media Technology"),
    "2215": ("Engineering", "Building and Construction"),
    "2216": ("Engineering", "Architecture"),
    "23": ("Environmental Science", "General"),
    "2300": ("Environmental Science", "General Environmental Science"),
    "2301": ("Environmental Science", "Environmental Science (miscellaneous)"),
    "2302": ("Environmental Science", "Ecological Modeling"),
    "2303": ("Environmental Science", "Ecology"),
    "2304": ("Environmental Science", "Environmental Chemistry"),
    "2305": ("Environmental Science", "Environmental Engineering"),
    "2306": ("Environmental Science", "Global and Planetary Change"),
    "2307": ("Environmental Science", "Health, Toxicology and Mutagenesis"),
    "2308": ("Environmental Science", "Management, Monitoring, Policy and Law"),
    "2309": ("Environmental Science", "Nature and Landscape Conservation"),
    "2310": ("Environmental Science", "Pollution"),
    "2311": ("Environmental Science", "Waste Management and Disposal"),
    "2312": ("Environmental Science", "Water Science and Technology"),
    "24": ("Immunology and Microbiology", "General"),
    "2400": ("Immunology and Microbiology", "General Immunology and Microbiology"),
    "2401": ("Immunology and Microbiology", "Immunology and Microbiology (miscellaneous)"),
    "2402": ("Immunology and Microbiology", "Applied Microbiology and Biotechnology"),
    "2403": ("Immunology and Microbiology", "Immunology"),
    "2404": ("Immunology and Microbiology", "Microbiology"),
    "2405": ("Immunology and Microbiology", "Parasitology"),
    "2406": ("Immunology and Microbiology", "Virology"),
    "25": ("Materials Science", "General"),
    "2500": ("Materials Science", "General Materials Science"),
    "2501": ("Materials Science", "Materials Science (miscellaneous)"),
    "2502": ("Materials Science", "Biomaterials"),
    "2503": ("Materials Science", "Ceramics and Composites"),
    "2504": ("Materials Science", "Electronic, Optical and Magnetic Materials"),
    "2505": ("Materials Science", "Materials Chemistry"),
    "2506": ("Materials Science", "Metals and Alloys"),
    "2507": ("Materials Science", "Polymers and Plastics"),
    "2508": ("Materials Science", "Surfaces, Coatings and Films"),
    "26": ("Mathematics", "General"),
    "2600": ("Mathematics", "General Mathematics"),
    "2601": ("Mathematics", "Mathematics (miscellaneous)"),
    "2602": ("Mathematics", "Algebra and Number Theory"),
    "2603": ("Mathematics", "Analysis"),
    "2604": ("Mathematics", "Applied Mathematics"),
    "2605": ("Mathematics", "Computational Mathematics"),
    "2606": ("Mathematics", "Control and Optimization"),
    "2607": ("Mathematics", "Discrete Mathematics and Combinatorics"),
    "2608": ("Mathematics", "Geometry and Topology"),
    "2609": ("Mathematics", "Logic"),
    "2610": ("Mathematics", "Mathematical Physics"),
    "2611": ("Mathematics", "Modelling and Simulation"),
    "2612": ("Mathematics", "Numerical Analysis"),
    "2613": ("Mathematics", "Statistics and Probability"),
    "2614": ("Mathematics", "Theoretical Computer Science"),
    "27": ("Medicine", "General"),
    "2700": ("Medicine", "General Medicine"),
    "2701": ("Medicine", "Medicine (miscellaneous)"),
    "2702": ("Medicine", "Anatomy"),
    "2703": ("Medicine", "Anesthesiology and Pain Medicine"),
    "2704": ("Medicine", "Biochemistry, medical"),
    "2705": ("Medicine", "Cardiology and Cardiovascular Medicine"),
    "2706": ("Medicine", "Critical Care and Intensive Care Medicine"),
    "2707": ("Medicine", "Complementary and alternative medicine"),
    "2708": ("Medicine", "Dermatology"),
    "2709": ("Medicine", "Drug guides"),
    "2710": ("Medicine", "Embryology"),
    "2711": ("Medicine", "Emergency Medicine"),
    "2712": ("Medicine", "Endocrinology, Diabetes and Metabolism"),
    "2713": ("Medicine", "Epidemiology"),
    "2714": ("Medicine", "Family Practice"),
    "2715": ("Medicine", "Gastroenterology"),
    "2716": ("Medicine", "Genetics(clinical)"),
    "2717": ("Medicine", "Geriatrics and Gerontology"),
    "2718": ("Medicine", "Health Informatics"),
    "2719": ("Medicine", "Health Policy"),
    "2720": ("Medicine", "Hematology"),
    "2721": ("Medicine", "Hepatology"),
    "2722": ("Medicine", "Histology"),
    "2723": ("Medicine", "Immunology and Allergy"),
    "2724": ("Medicine", "Internal Medicine"),
    "2725": ("Medicine", "Infectious Diseases"),
    "2726": ("Medicine", "Microbiology (medical)"),
    "2727": ("Medicine", "Nephrology"),
    "2728": ("Medicine", "Clinical Neurology"),
    "2729": ("Medicine", "Obstetrics and Gynaecology"),
    "2730": ("Medicine", "Oncology"),
    "2731": ("Medicine", "Ophthalmology"),
    "2732": ("Medicine", "Orthopedics and Sports Medicine"),
    "2733": ("Medicine", "Otorhinolaryngology"),
    "2734": ("Medicine", "Pathology and Forensic Medicine"),
    "2735": ("Medicine", "Pediatrics, Perinatology, and Child Health"),
    "2736": ("Medicine", "Pharmacology (medical)"),
    "2737": ("Medicine", "Physiology (medical)"),
    "2738": ("Medicine", "Psychiatry and Mental health"),
    "2739": ("Medicine", "Public Health, Environmental and Occupational Health"),
    "2740": ("Medicine", "Pulmonary and Respiratory Medicine"),
    "2741": ("Medicine", "Radiology Nuclear Medicine and imaging"),
    "2742": ("Medicine", "Rehabilitation"),
    "2743": ("Medicine", "Reproductive Medicine"),
    "2744": ("Medicine", "Reviews and References, Medical"),
    "2745": ("Medicine", "Rheumatology"),
    "2746": ("Medicine", "Surgery"),
    "2747": ("Medicine", "Transplantation"),
    "2748": ("Medicine", "Urology"),
    "28": ("Neuroscience", "General"),
    "2800": ("Neuroscience", "General Neuroscience"),
    "2801": ("Neuroscience", "Neuroscience (miscellaneous)"),
    "2802": ("Neuroscience", "Behavioral Neuroscience"),
    "2803": ("Neuroscience", "Biological Psychiatry"),
    "2804": ("Neuroscience", "Cellular and Molecular Neuroscience"),
    "2805": ("Neuroscience", "Cognitive Neuroscience"),
    "2806": ("Neuroscience", "Developmental Neuroscience"),
    "2807": ("Neuroscience", "Endocrine and Autonomic Systems"),
    "2808": ("Neuroscience", "Neurology"),
    "2809": ("Neuroscience", "Sensory Systems"),
    "29": ("Nursing", "General"),
    "2900": ("Nursing", "General Nursing"),
    "2901": ("Nursing", "Nursing (miscellaneous)"),
    "2902": ("Nursing", "Advanced and Specialised Nursing"),
    "2903": ("Nursing", "Assessment and Diagnosis"),
    "2904": ("Nursing", "Care Planning"),
    "2905": ("Nursing", "Community and Home Care"),
    "2906": ("Nursing", "Critical Care"),
    "2907": ("Nursing", "Emergency"),
    "2908": ("Nursing", "Fundamentals and skills"),
    "2909": ("Nursing", "Gerontology"),
    "2910": ("Nursing", "Issues, ethics and legal aspects"),
    "2911": ("Nursing", "Leadership and Management"),
    "2912": ("Nursing", "LPN and LVN"),
    "2913": ("Nursing", "Maternity and Midwifery"),
    "2914": ("Nursing", "Medical-Surgical"),
    "2915": ("Nursing", "Nurse Assisting"),
    "2916": ("Nursing", "Nutrition and Dietetics"),
    "2917": ("Nursing", "Oncology (nursing)"),
    "2918": ("Nursing", "Pathophysiology"),
    "2919": ("Nursing", "Pediatrics"),
    "2920": ("Nursing", "Pharmacology (nursing)"),
    "2921": ("Nursing", "Psychiatric Mental Health"),
    "2922": ("Nursing", "Research and Theory"),
    "2923": ("Nursing", "Review and Exam Preparation"),
    "30": ("Pharmacology, Toxicology and Pharmaceutics", "General"),
    "3000": ("Pharmacology, Toxicology and Pharmaceutics", "General Pharmacology, Toxicology and Pharmaceutics"),
    "3001": ("Pharmacology, Toxicology and Pharmaceutics", "Pharmacology, Toxicology and Pharmaceutics (miscellaneous)"),
    "3002": ("Pharmacology, Toxicology and Pharmaceutics", "Drug Discovery"),
    "3003": ("Pharmacology, Toxicology and Pharmaceutics", "Pharmaceutical Science"),
    "3004": ("Pharmacology, Toxicology and Pharmaceutics", "Pharmacology"),
    "3005": ("Pharmacology, Toxicology and Pharmaceutics", "Toxicology"),
    "31": ("Physics and Astronomy", "General"),
    "3100": ("Physics and Astronomy", "General Physics and Astronomy"),
    "3101": ("Physics and Astronomy", "Physics and Astronomy (miscellaneous)"),
    "3102": ("Physics and Astronomy", "Acoustics and Ultrasonics"),
    "3103": ("Physics and Astronomy", "Astronomy and Astrophysics"),
    "3104": ("Physics and Astronomy", "Condensed Matter Physics"),
    "3105": ("Physics and Astronomy", "Instrumentation"),
    "3106": ("Physics and Astronomy", "Nuclear and High Energy Physics"),
    "3107": ("Physics and Astronomy", "Atomic and Molecular Physics, and Optics"),
    "3108": ("Physics and Astronomy", "Radiation"),
    "3109": ("Physics and Astronomy", "Statistical and Nonlinear Physics"),
    "3110": ("Physics and Astronomy", "Surfaces and Interfaces"),
    "32": ("Psychology", "General"),
    "3200": ("Psychology", "General Psychology"),
    "3201": ("Psychology", "Psychology (miscellaneous)"),
    "3202": ("Psychology", "Applied Psychology"),
    "3203": ("Psychology", "Clinical Psychology"),
    "3204": ("Psychology", "Developmental and Educational Psychology"),
    "3205": ("Psychology", "Experimental and Cognitive Psychology"),
    "3206": ("Psychology", "Neuropsychology and Physiological Psychology"),
    "3207": ("Psychology", "Social Psychology"),
    "33": ("Social Sciences", "General"),
    "3300": ("Social Sciences", "General Social Sciences"),
    "3301": ("Social Sciences", "Social Sciences (miscellaneous)"),
    "3302": ("Social Sciences", "Archaeology"),
    "3303": ("Social Sciences", "Development"),
    "3304": ("Social Sciences", "Education"),
    "3305": ("Social Sciences", "Geography, Planning and Development"),
    "3306": ("Social Sciences", "Health (social science)"),
    "3307": ("Social Sciences", "Human Factors and Ergonomics"),
    "3308": ("Social Sciences", "Law"),
    "3309": ("Social Sciences", "Library and Information Sciences"),
    "3310": ("Social Sciences", "Linguistics and Language"),
    "3311": ("Social Sciences", "Safety Research"),
    "3312": ("Social Sciences", "Sociology and Political Science"),
    "3313": ("Social Sciences", "Transportation"),
    "3314": ("Social Sciences", "Anthropology"),
    "3315": ("Social Sciences", "Communication"),
    "3316": ("Social Sciences", "Cultural Studies"),
    "3317": ("Social Sciences", "Demography"),
    "3318": ("Social Sciences", "Gender Studies"),
    "3319": ("Social Sciences", "Life-span and Life-course Studies"),
    "3320": ("Social Sciences", "Political Science and International Relations"),
    "3321": ("Social Sciences", "Public Administration"),
    "3322": ("Social Sciences", "Urban Studies"),
    "34": ("Veterinary", "General"),
    "3400": ("Veterinary", "General Veterinary"),
    "3401": ("Veterinary", "Veterinary (miscellaneous)"),
    "3402": ("Veterinary", "Equine"),
    "3403": ("Veterinary", "Food Animals"),
    "3404": ("Veterinary", "Small Animals"),
    "35": ("Dentistry", "General"),
    "3500": ("Dentistry", "General Dentistry"),
    "3501": ("Dentistry", "Dentistry (miscellaneous)"),
    "3502": ("Dentistry", "Dental Assisting"),
    "3503": ("Dentistry", "Dental Hygiene"),
    "3504": ("Dentistry", "Oral Surgery"),
    "3505": ("Dentistry", "Orthodontics"),
    "3506": ("Dentistry", "Periodontics"),
    "36": ("Health Professions", "General"),
    "3600": ("Health Professions", "General Health Professions"),
    "3601": ("Health Professions", "Health Professions (miscellaneous)"),
    "3602": ("Health Professions", "Chiropractics"),
    "3603": ("Health Professions", "Complementary and Manual Therapy"),
    "3604": ("Health Professions", "Emergency Medical Services"),
    "3605": ("Health Professions", "Health Information Management"),
    "3606": ("Health Professions", "Medical Assisting and Transcription"),
    "3607": ("Health Professions", "Medical Laboratory Technology"),
    "3608": ("Health Professions", "Medical Terminology"),
    "3609": ("Health Professions", "Occupational Therapy"),
    "3610": ("Health Professions", "Optometry"),
    "3611": ("Health Professions", "Pharmacy"),
    "3612": ("Health Professions", "Physical Therapy, Sports Therapy and Rehabilitation"),
    "3613": ("Health Professions", "Podiatry"),
    "3614": ("Health Professions", "Radiological and Ultrasound Technology"),
    "3615": ("Health Professions", "Respiratory Care"),
    "3616": ("Health Professions", "Speech and Hearing"),
}

COUNTRIES_TO_CHECK = [
    "United States", "China", "United Kingdom", "Germany", "Japan",
    "France", "Canada", "Australia", "Italy", "Spain",
    "South Korea", "India", "Netherlands", "Brazil", "Switzerland",
    "Sweden", "Poland", "Turkey", "Iran", "Portugal",
    "Belgium", "Denmark", "Norway", "Finland", "Austria",
    "Czech Republic", "Greece", "Israel", "New Zealand", "Singapore",
    "Argentina", "Mexico", "South Africa", "Russia", "Taiwan",
    "Malaysia", "Thailand", "Egypt", "Saudi Arabia", "Nigeria",
    "Colombia", "Chile", "Indonesia", "Pakistan", "Romania",
    "Hungary", "Slovakia", "Croatia", "Serbia", "Ukraine",
    "Peru", "Vietnam", "Morocco", "Tunisia", "Kenya",
]

WOS_COLLECTIONS = {
    "WOS.SCI":  "Science Citation Index Expanded (SCIE)",
    "WOS.SSCI": "Social Sciences Citation Index (SSCI)",
    "WOS.AHCI": "Arts & Humanities Citation Index (AHCI)",
    "WOS.ESCI": "Emerging Sources Citation Index (ESCI)",
    "WOS.ISTP": "Conference Proceedings Citation Index (CPCI)",
}

JCR_CATEGORIES = [
    "Acoustics", "Agricultural Economics & Policy", "Agricultural Engineering",
    "Agriculture Dairy & Animal Science", "Agriculture Multidisciplinary",
    "Agronomy", "Allergy", "Anatomy & Morphology", "Andrology",
    "Anesthesiology", "Anthropology", "Area Studies",
    "Astronomy & Astrophysics", "Automation & Control Systems",
    "Behavioral Sciences", "Biochemical Research Methods",
    "Biochemistry & Molecular Biology", "Biodiversity Conservation",
    "Biology", "Biophysics", "Biotechnology & Applied Microbiology",
    "Cardiac & Cardiovascular Systems", "Cell Biology",
    "Chemistry Analytical", "Chemistry Applied",
    "Chemistry Inorganic & Nuclear", "Chemistry Medicinal",
    "Chemistry Multidisciplinary", "Chemistry Organic",
    "Chemistry Physical", "Clinical Neurology", "Communication",
    "Computer Science Artificial Intelligence",
    "Computer Science Cybernetics",
    "Computer Science Hardware & Architecture",
    "Computer Science Information Systems",
    "Computer Science Interdisciplinary Applications",
    "Computer Science Software Engineering",
    "Computer Science Theory & Methods", "Construction & Building Technology",
    "Critical Care Medicine", "Crystallography", "Dentistry Oral Surgery & Medicine",
    "Dermatology & Venerereal Diseases", "Developmental Biology",
    "Ecology", "Economics", "Education & Educational Research",
    "Education Scientific Disciplines", "Electrochemistry",
    "Emergency Medicine", "Endocrinology & Metabolism",
    "Energy & Fuels", "Engineering Aerospace",
    "Engineering Biomedical", "Engineering Chemical",
    "Engineering Environmental", "Engineering Geological",
    "Engineering Industrial", "Engineering Manufacturing",
    "Engineering Marine", "Engineering Mechanical",
    "Engineering Multidisciplinary", "Engineering Ocean",
    "Engineering Petroleum", "Entomology", "Environmental Sciences",
    "Environmental Studies", "Ergonomics", "Evolutionary Biology",
    "Fisheries", "Food Science & Technology", "Forestry",
    "Gastroenterology & Hepatology", "Genetics & Heredity",
    "Geochemistry & Geophysics", "Geography", "Geography Physical",
    "Geology", "Geosciences Multidisciplinary", "Geriatrics & Gerontology",
    "Gerontology", "Green & Sustainable Science & Technology",
    "Health Care Sciences & Services", "Health Policy & Services",
    "Hematology", "History & Philosophy of Science",
    "Horticulture", "Hospitality Leisure Sport & Tourism",
    "Imaging Science & Photographic Technology", "Immunology",
    "Infectious Diseases", "Information Science & Library Science",
    "Instruments & Instrumentation", "Integrative & Complementary Medicine",
    "International Relations", "Marine & Freshwater Biology",
    "Materials Science Biomaterials", "Materials Science Ceramics",
    "Materials Science Characterization & Testing",
    "Materials Science Coatings & Films", "Materials Science Composites",
    "Materials Science Multidisciplinary", "Materials Science Paper & Wood",
    "Materials Science Textiles", "Mathematical & Computational Biology",
    "Mathematics", "Mathematics Applied", "Mathematics Interdisciplinary Applications",
    "Mechanics", "Medical Ethics", "Medical Informatics",
    "Medical Laboratory Technology", "Medicine General & Internal",
    "Medicine Legal", "Medicine Research & Experimental",
    "Metallurgy & Metallurgical Engineering", "Meteorology & Atmospheric Sciences",
    "Microbiology", "Microscopy", "Mineralogy", "Mining & Mineral Processing",
    "Multidisciplinary Sciences", "Mycology", "Nanoscience & Nanotechnology",
    "Neuroimaging", "Neurosciences", "Nuclear Science & Technology",
    "Nursing", "Nutrition & Dietetics", "Obstetrics & Gynecology",
    "Oceanography", "Oncology", "Operations Research & Management Science",
    "Ophthalmology", "Optics", "Orthopedics", "Otorhinolaryngology",
    "Paleontology", "Parasitology", "Pathology", "Pediatrics",
    "Peripheral Vascular Disease", "Pharmacology & Pharmacy",
    "Physics Applied", "Physics Atomic Molecular & Chemical",
    "Physics Condensed Matter", "Physics Fluids & Plasmas",
    "Physics Mathematical", "Physics Multidisciplinary",
    "Physics Nuclear", "Physics Particles & Fields",
    "Physiology", "Plant Sciences", "Polymer Science",
    "Primary Health Care", "Psychiatry", "Psychology",
    "Psychology Applied", "Psychology Biological",
    "Psychology Clinical", "Psychology Developmental",
    "Psychology Educational", "Psychology Experimental",
    "Psychology Mathematical", "Psychology Multidisciplinary",
    "Psychology Social","Political Science", "Public Administration",
    "Public Environmental & Occupational Health",
    "Radiology Nuclear Medicine & Medical Imaging",
    "Rehabilitation", "Remote Sensing", "Reproductive Biology",
    "Respiratory System", "Rheumatology", "Robotics",
    "Social Issues", "Social Sciences Biomedical",
    "Social Sciences Interdisciplinary", "Social Sciences Mathematical Methods",
    "Social Work", "Sociology", "Soil Science", "Spectroscopy",
    "Sport Sciences", "Statistics & Probability", "Substance Abuse",
    "Surgery", "Telecommunications", "Thermodynamics",
    "Toxicology", "Transplantation", "Transportation",
    "Transportation Science & Technology", "Tropical Medicine",
    "Urban Studies", "Urology & Nephrology", "Veterinary Sciences",
    "Virology", "Water Resources", "Women's Studies", "Zoology"
]
